dist: trusty


sudo: required

language: java
before_install:
  - "sudo apt-get remove openjdk-7-jdk"
  - "sudo add-apt-repository -y ppa:openjdk-r/ppa"
  - "sudo apt-get update"
  - "sudo apt-get install openjdk-7-jre-headless=7u51-2.4.6-1ubuntu4"
  - "sudo apt-get install openjdk-7-jre=7u51-2.4.6-1ubuntu4"
  - "sudo apt-get install openjdk-7-jdk=7u51-2.4.6-1ubuntu4"
#- "sudo apt-get --allow-downgrages install openjdk-7-jre=7u51-2.4.6-1ubuntu4"
#- "./gradlew -version"
install: "./gradlew assemble"
script: "./gradlew clean travisbuild"
jdk:
- openjdk7
addons:
  artifacts:
    paths:
    - zips/
    target_paths: artifacts/$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER
    s3_region: us-east-1
env:
  matrix:
    secure: gOEl7TFI3RH0cMkSNOXeSwC0ZCF60/JSftuTK0Y7UZtSS4yEYkn4o2RX/PO3I+3kQdpkbx9pe+lnd1+C1to1QJqd4AhOGwoy/7KvTE+qCP0bdOLSWUbWJ92SmI/ZPijnODfcFWWkCDIhQBK0SEinVokjD5PPobDwGMosDMS2Qzo=
